### ISSUE TITLE
字体

### ISSUE THREAD

**Issue by skeeey** [skeeey/note#16]
## 字体分类

- Serif，如：Georgia, Times New Roman, 宋体
- Sans-Serif，如：Arial, Tahoma, Verdana, Trebuchet MS, Helvetica, 黑体
- Monospace 等宽字体，如：Courier New
- 其它：scripts 手写体（比如花体）、blackletter 铅字体、ornamental 装饰体和 symbol 符号字体

![](http://ww1.sinaimg.cn/large/630b6069gy1fffcbv1s1fj208904f3yd.jpg)

### Serif 与 Sans-Serif 的区别
- Serif 的字体容易辨认，易读性较高，而 Sans-Serif 则较醒目。
- Serif 强调了字母笔划的开始及结束，因此较易前后连续性的辨识。
- Serif 强调一个 word，而非单一的字母，Sans-Serif 则强调个别字母。
- 在小字体的场合，通常 Sans-Serif 比 Serif 更清晰。

因此，Serif 字体适用于正文等需要长时间阅读的情形，而 Sans-Serif 字体适用于标题、表格内用字，等需要显着、醒目，但不必长时间盯着这些字来阅的情形

## CSS font

```css
/* 声明顺序: font-size, font-family */
/* 12px/1.5：12px 字体大小，1.5 line-height，如果有单位，
则继承自该节点的元素会直接使用计算结果 */
/* sans-serif：一般在字体声明的最后指定一个 sans-serif 
这样的 Generic-family，在客户端没有指定字体时，使用客户端的默认字体 */
{font: 12px/1.5 Tahoma, Helvetica, Arial, sans-serif;}
```
### ```em``` 与 ```rem```
- ```em```，相对于当前对象的 parent 的文本的字体大小
- ```rem```，root em，相对于 root 元素（```<html>```）字体的大小

> 响应式：在 ```body``` 元素上使用百分比（基于父元素的一个百分比值）， 如 ```body { font-size: 62.5%; }```，然后使用 ```em``` 单位调整具体的字体。

## 参考
- [CSS font](http://www.w3school.com.cn/cssref/pr_font_font.asp)
